### ISSUE TITLE
Local env | Not Streaming to Kinesis Stream

### ISSUE THREAD

**Issue by dev2612** [brain-power/Brain-Power-Amazon-Fidgetology#12]
Hello,

Am a newbie to Kinesis. Have tried to setup the project in all three mentioned ways in the readme but cannot make it to work.

Local Env: I have setup all required versions and did intall the project. NPM start gives following  response.

`<addr>`
         > node server.js

Express HTTP server listening on port 3000

Uploads bucket:  brain-power-fidgetology-demo-uploads-862986627627

GET / 304 4.464 ms - -
GET /css/main.css 304 7.172 ms - -
GET /js/app/config.js 404 14.544 ms - 155
GET /js/lib/aws-sdk/aws-sdk.min.js 304 15.438 ms - -
GET /js/lib/font-awesome/fontawesome-all.min.js 304 14.277 ms - -
GET /js/lib/echarts/echarts.min.js 304 13.420 ms - -
GET /js/lib/ng-file-upload/ng-file-upload.min.js 304 12.919 ms - -
GET /js/lib/ng-file-upload/ng-file-upload-shim.min.js 304 12.457 ms - -
GET /js/lib/webcamjs/webcam.js 304 7.609 ms - -
GET /js/custom/frame-buffer.js 304 7.896 ms - -
GET /js/app/ng-config.js 304 13.389 ms - -
GET /js/app/webcam-stream-controller.js 304 13.743 ms - -
GET /js/app/chart-controllers/metrics-chart-controller.js 304 13.544 ms - -
GET /js/app/root-controller.js 304 13.424 ms - -
GET /js/app/chart-controllers/fidgetometer-controller.js 304 1.017 ms - -
GET /js/app/config.js 404 1.100 ms - 155
GET /Prod/Config 404 0.551 ms - 150
GET /favicon.ico 200 2.356 ms - 1150
`<addr>`

The camera stream starts on browser but nothing gets posted to kinesis 

Please help.

**Comment by runpengl** [comment]
Did you first deploy the Cloudformation stack via the command line using `./deploy_example.sh`?
Testing in local environment will only work once the stack deployed to AWS via command line.
Please follow all instructions in the previous section of the README (**"Command Line Deployment"**), and install all dependencies needed for development and testing.

**Comment by dev2612** [comment]
Thanks for responding. 
Yes I tried that but it fails

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/49262326/60329717-d0d91380-9988-11e9-8087-d2d8320f98c0.png">

**Comment by runpengl** [comment]
Seems like you'll need to sign-in to the AWS console, delete the existing CloudFormation stack (because it's stuck in a bad state), and start fresh.
