### ISSUE TITLE
Real-time analytics not working

### ISSUE THREAD

**Issue by ezimerman** [brain-power/Brain-Power-Amazon-Fidgetology#18]
![image (4)](https://user-images.githubusercontent.com/8227644/66226389-ea7cac00-e697-11e9-86e4-623a55eada0d.png)

**Comment by runpengl** [comment]
Issue was due to the old ffmpeg package not being with compatible with AWS Lambda anymore.
Resolved by https://github.com/brain-power/Brain-Power-Amazon-Fidgetology/pull/21
