### ISSUE TITLE
client upload error

### ISSUE THREAD

**Issue by cyrfer** [brain-power/Brain-Power-Amazon-Fidgetology#19]
**PROBLEM**
I can run locally per the instructions, and I see my video from the browser on `localhost:3000`, but the frames do not make it to KVS.

![image](https://user-images.githubusercontent.com/4392990/67151451-5dcb1400-f27b-11e9-9372-632fc665ff4f.png)

There are some errors about `config.js` that might be related.

![image](https://user-images.githubusercontent.com/4392990/67151447-3411ed00-f27b-11e9-9798-ee0e02d10111.png)

**STEPS TO REPRODUCE**
Tested with Chrome on OSX and Nodejs 12.3.1.

1. click the button to Launch the Stack for `Full Version`
2. brew install ffmpeg
3. git clone git@github.com:brain-power/Brain-Power-Amazon-Fidgetology.git
4. cd Brain-Power-Amazon-Fidgetology; npm install; npm start
5. open http://localhost:3000
6. ./delete_stack.sh

**Comment by runpengl** [comment]
Issue was due to the old ffmpeg package not being with compatible with AWS Lambda anymore.
Resolved by https://github.com/brain-power/Brain-Power-Amazon-Fidgetology/pull/21
Please try again with fresh `npm install`
