### ISSUE TITLE
ffmpeg is not working in lambda function

### ISSUE THREAD

**Issue by ajienfin** [brain-power/Brain-Power-Amazon-Fidgetology#20]
We have configured this solution in to our aws account.
Now we are getting an error "ENOENT: no such file or directory, lstat '/tmp/_1573629857064.mkv'" from the api gateway..

![](https://lh3.googleusercontent.com/-ZDs4RpzO77U/Xcuwmd2AhyI/AAAAAAAAAHY/6qGAi2B08Hsgwjo4xIDy8WOSfdUn0YCzgCK8BGAsYHg/s0/2019-11-12.png)

**Comment by pyros-endgame** [comment]
Same issue here. I'm believing it's actually associated to the lambda. The logs here show that it doenst seem to be able to run gzip (or can't find it somehow). Not sure what the next steps would be aside from packaging in the gzip binaries itself

![image](https://user-images.githubusercontent.com/11553732/69024143-58461400-0976-11ea-8b64-3532334c2087.png)

**Comment by runpengl** [comment]
Resolved by https://github.com/brain-power/Brain-Power-Amazon-Fidgetology/pull/21
Lambda-compatible (linux-x64) ffmpeg binaries are now packaged during deployment.
