### ISSUE TITLE
Access Denied By S3ToKVSLambda Code URI s3://brain-power-fidgetology-demo-bootstrap

### ISSUE THREAD

**Issue by guanlinz** [brain-power/Brain-Power-Amazon-Fidgetology#24]
![image](https://user-images.githubusercontent.com/22729408/70804321-24350600-1df1-11ea-8042-e4d2aa13d6a9.png)

It seems like it need permission to access the s3 bucket or did i do something wrong？

**Comment by escully27** [comment]
how did you fix this?? facing the same issue! thx

**Comment by guanlinz** [comment]
It's been a while since I stuck in that issue,you should check all the cloudformation build stack error instead of this one because of maybe it's not the root error. and here is some potential hint for you
1) S3 Bucket policy
2) IAM role

If you still have problem in build this project, send me email: guanlinzhang@hotmail,let's sort this out together

**Comment by escully27** [comment]
Just emailed you -- thanks a million

**Comment by escully27** [comment]
I got the stream to work properly by using terminal to deploy the stack and npm to run locally. 

How can I stream audio with the video?? I see that its sending the frames as image and then converting to mkv, maybe possible to send the audio as a file, and package with in the mkv-> Stream?

Anyone out there? Thanks
